import { Member, Place, PlaceType } from './types';

export const placeTypes: PlaceType[] = [
  { id: 'cafe', label: '咖啡店' },
  { id: 'restaurant', label: '餐厅' },
  { id: 'filming-spot', label: '拍摄地' },
  { id: 'other', label: '其他' }
];

export const members: Member[] = [
  { id: 'taeyong', englishName: 'Taeyong', displayName: 'Taeyong', aliases: ['李泰容', '??'] },
  { id: 'jaehyun', englishName: 'Jaehyun', displayName: 'Jaehyun', aliases: ['郑在玹', '??'] },
  { id: 'mark', englishName: 'Mark', displayName: 'Mark', aliases: ['李马克', '??'] },
  { id: 'haechan', englishName: 'Haechan', displayName: 'Haechan', aliases: ['Lee Donghyuck', '李东赫', '??'] },
  { id: 'yuta', englishName: 'Yuta', displayName: 'Yuta', aliases: ['中本悠太', '??'] },
  { id: 'doyoung', englishName: 'Doyoung', displayName: 'Doyoung', aliases: ['金道英', '??'] },
  { id: 'johnny', englishName: 'Johnny', displayName: 'Johnny', aliases: ['徐英浩', '??'] },
  { id: 'jungwoo', englishName: 'Jungwoo', displayName: 'Jungwoo', aliases: ['金廷祐', '??'] }
];

const baseImages = [
  'https://images.unsplash.com/photo-1554118811-1e0d58224f24',
  'https://images.unsplash.com/photo-1552566626-52f8b828add9',
  'https://images.unsplash.com/photo-1555992336-03a23c7b20ee'
];

export const places: Place[] = [
  {
    id: 'place-1',
    name: 'Myeongdong Cloud Cafe',
    address: '12 Myeongdong-gil, Jung-gu, Seoul',
    englishName: 'Myeongdong Cloud Cafe',
    koreanName: '?? ???? ??',
    englishAddress: '12 Myeongdong-gil, Jung-gu, Seoul',
    koreanAddress: '????? ?? ??? 12',
    latitude: 37.5637,
    longitude: 126.983,
    memberIds: ['taeyong', 'mark'],
    placeTypeId: 'cafe',
    description: 'A hanok-adjacent cafe that appears often in fan logs, known for slow afternoons and soft city light.',
    descriptionZh: '粉丝日志里高频出现的咖啡店，适合放慢节奏，边休息边补完巡礼照片。',
    moodTags: ['classic', 'photo-spot'],
    images: [baseImages[0]],
    sourceNote: 'Fan photo thread'
  },
  {
    id: 'place-2',
    name: 'Hongdae Neon Bites',
    address: '41 Wausan-ro, Mapo-gu, Seoul',
    englishName: 'Hongdae Neon Bites',
    koreanName: '?? ?? ???',
    englishAddress: '41 Wausan-ro, Mapo-gu, Seoul',
    koreanAddress: '????? ??? ???? 41',
    latitude: 37.5568,
    longitude: 126.9245,
    memberIds: ['jaehyun', 'jungwoo'],
    placeTypeId: 'restaurant',
    description: 'A late-night table that gained attention after member mentions, popular for post-concert fan meetups.',
    descriptionZh: '成员提及后热度上升的夜宵餐厅，演出结束后很多粉丝会来这里集合。',
    moodTags: ['hot'],
    images: [baseImages[1]]
  },
  {
    id: 'place-3',
    name: 'Apgujeong Vinyl Shop',
    address: '88 Apgujeong-ro, Gangnam-gu, Seoul',
    englishName: 'Apgujeong Vinyl Shop',
    koreanName: '??? ??? ?',
    englishAddress: '88 Apgujeong-ro, Gangnam-gu, Seoul',
    koreanAddress: '????? ??? ???? 88',
    latitude: 37.5273,
    longitude: 127.0286,
    memberIds: ['johnny', 'doyoung'],
    placeTypeId: 'other',
    description: 'A hidden stop for fans who like records, styling props, and quieter corners away from main streets.',
    descriptionZh: '适合慢逛的隐藏据点，收藏黑胶和生活方式小物的粉丝会很喜欢。',
    moodTags: ['hidden', 'classic'],
    images: [baseImages[2]]
  },
  {
    id: 'place-4',
    name: 'Han River Sunset Deck',
    address: '330 Yeouidong-ro, Yeongdeungpo-gu, Seoul',
    englishName: 'Han River Sunset Deck',
    koreanName: '?? ?? ?',
    englishAddress: '330 Yeouidong-ro, Yeongdeungpo-gu, Seoul',
    koreanAddress: '????? ???? ???? 330',
    latitude: 37.5283,
    longitude: 126.932,
    memberIds: ['yuta', 'haechan'],
    placeTypeId: 'filming-spot',
    description: 'A riverfront filming point where fans pause for skyline shots and evening walks between destinations.',
    descriptionZh: '临江拍摄点，很多粉丝会在这里拍天际线，再继续下一站巡礼。',
    moodTags: ['photo-spot', 'classic'],
    images: [baseImages[0], baseImages[1]]
  },
  {
    id: 'place-5',
    name: 'Ikseon Bloom House',
    address: '17 Supyo-ro 28-gil, Jongno-gu, Seoul',
    englishName: 'Ikseon Bloom House',
    koreanName: '?? ?? ???',
    englishAddress: '17 Supyo-ro 28-gil, Jongno-gu, Seoul',
    koreanAddress: '????? ??? ???28? 17',
    latitude: 37.5742,
    longitude: 126.9892,
    memberIds: ['doyoung', 'taeyong'],
    placeTypeId: 'cafe',
    description: 'A hanok cafe frequently visited by fans, perfect for a slower pilgrimage stop in Ikseon alleys.',
    descriptionZh: '??洞里很受欢迎的韩屋咖啡店，适合把巡礼节奏放慢。',
    moodTags: ['hot', 'photo-spot'],
    images: [baseImages[1]]
  },
  {
    id: 'place-6',
    name: 'COEX Plaza Corner',
    address: '513 Yeongdong-daero, Gangnam-gu, Seoul',
    englishName: 'COEX Plaza Corner',
    koreanName: '??? ??? ??',
    englishAddress: '513 Yeongdong-daero, Gangnam-gu, Seoul',
    koreanAddress: '????? ??? ???? 513',
    latitude: 37.5117,
    longitude: 127.0592,
    memberIds: ['mark', 'johnny', 'jungwoo'],
    placeTypeId: 'other',
    description: 'A classic fan meeting point where routes often start before heading to cafes and filming spots.',
    descriptionZh: '经典集合点，很多巡礼路线都会从这里出发。',
    moodTags: ['classic'],
    images: [baseImages[2]]
  },
  {
    id: 'place-7',
    name: 'Jamsil Rooftop Grill',
    address: '240 Olympic-ro, Songpa-gu, Seoul',
    englishName: 'Jamsil Rooftop Grill',
    koreanName: '?? ??? ??',
    englishAddress: '240 Olympic-ro, Songpa-gu, Seoul',
    koreanAddress: '????? ??? ???? 240',
    latitude: 37.513,
    longitude: 127.1027,
    memberIds: ['jaehyun', 'yuta'],
    placeTypeId: 'restaurant',
    description: 'A dinner stop with rooftop night views, often recommended for fans wrapping up a long route day.',
    descriptionZh: '夜景氛围很好的屋顶餐厅，适合巡礼一天结束时来这里收尾。',
    moodTags: ['classic', 'photo-spot'],
    images: [baseImages[0]]
  },
  {
    id: 'place-8',
    name: 'Seongsu Craft Alley',
    address: '8 Yeonmujang 5-gil, Seongdong-gu, Seoul',
    englishName: 'Seongsu Craft Alley',
    koreanName: '?? ???? ??',
    englishAddress: '8 Yeonmujang 5-gil, Seongdong-gu, Seoul',
    koreanAddress: '????? ??? ???5? 8',
    latitude: 37.5443,
    longitude: 127.0557,
    memberIds: ['taeyong', 'haechan', 'mark'],
    placeTypeId: 'other',
    description: 'A hidden alley for design shops and fan-photo corners, ideal for unhurried walking routes.',
    descriptionZh: '藏在巷子里的设计区，边走边拍很舒服，适合慢速巡礼。',
    moodTags: ['hidden', 'photo-spot'],
    images: [baseImages[2], baseImages[1]]
  },
  {
    id: 'place-9',
    name: 'Namsan Steps Scene',
    address: '105 Namsangongwon-gil, Yongsan-gu, Seoul',
    englishName: 'Namsan Steps Scene',
    koreanName: '?? ??? ?',
    englishAddress: '105 Namsangongwon-gil, Yongsan-gu, Seoul',
    koreanAddress: '????? ??? ????? 105',
    latitude: 37.5512,
    longitude: 126.9882,
    memberIds: ['doyoung', 'jaehyun'],
    placeTypeId: 'filming-spot',
    description: 'A recognizable filming staircase and one of the most re-created fan photo compositions in Seoul.',
    descriptionZh: '辨识度很高的拍摄阶梯，是粉丝复刻构图的热门地点。',
    moodTags: ['hot', 'photo-spot'],
    images: [baseImages[0]]
  },
  {
    id: 'place-10',
    name: 'Yeonnam Berry Cafe',
    address: '32 Donggyo-ro 38-gil, Mapo-gu, Seoul',
    englishName: 'Yeonnam Berry Cafe',
    koreanName: '?? ?? ??',
    englishAddress: '32 Donggyo-ro 38-gil, Mapo-gu, Seoul',
    koreanAddress: '????? ??? ???38? 32',
    latitude: 37.5625,
    longitude: 126.9258,
    memberIds: ['jungwoo', 'johnny'],
    placeTypeId: 'cafe',
    description: 'A photo-friendly cafe known in fan diaries, popular for bright table shots and dessert breaks.',
    descriptionZh: '在粉丝打卡帖里出镜率很高的咖啡店，适合拍桌面和甜品照。',
    moodTags: ['hot', 'photo-spot'],
    images: [baseImages[1]]
  },
  {
    id: 'place-11',
    name: 'Itaewon Night Noodles',
    address: '19 Itaewon-ro 27ga-gil, Yongsan-gu, Seoul',
    englishName: 'Itaewon Night Noodles',
    koreanName: '??? ??? ??',
    englishAddress: '19 Itaewon-ro 27ga-gil, Yongsan-gu, Seoul',
    koreanAddress: '????? ??? ????27?? 19',
    latitude: 37.5341,
    longitude: 126.9946,
    memberIds: ['mark', 'haechan'],
    placeTypeId: 'restaurant',
    description: 'A low-key late-night noodle stop that appears in fan route recaps after evening schedules.',
    descriptionZh: '低调但很实用的夜间面馆，常见于粉丝晚场后路线复盘。',
    moodTags: ['hidden'],
    images: [baseImages[2]]
  },
  {
    id: 'place-12',
    name: 'Gangnam Photo Tunnel',
    address: '152 Teheran-ro, Gangnam-gu, Seoul',
    englishName: 'Gangnam Photo Tunnel',
    koreanName: '?? ?? ??',
    englishAddress: '152 Teheran-ro, Gangnam-gu, Seoul',
    koreanAddress: '????? ??? ???? 152',
    latitude: 37.5004,
    longitude: 127.0369,
    memberIds: ['yuta', 'taeyong', 'doyoung'],
    placeTypeId: 'filming-spot',
    description: 'A hidden pilgrimage spot for dramatic tunnel shots, best visited during quieter evening hours.',
    descriptionZh: '偏隐藏的拍摄点，夜间光影更有氛围，适合拍有舞台感的照片。',
    moodTags: ['hidden', 'photo-spot'],
    images: [baseImages[0], baseImages[2]],
    sourceNote: 'Companion fan map list'
  }
];

